# Generated by Django 5.2.4 on 2025-11-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_wishlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
